pipeline {
  environment {
    RANCHER_STACKID = "{{ cookiecutter.rancher_stackid }}"
    RANCHER_ENVID = "{{ cookiecutter.rancher_envid }}"
    GIT_NAME = "{{ cookiecutter.project_slug }}"
    registry = "{{ cookiecutter.__docker_image }}"
    template = "templates/{{ cookiecutter.project_slug }}"
    dockerImage = ''
    tagName = ''
    SONARQUBE_TAG = '{{ cookiecutter.sonarqube_tag }}'
  }

  agent any

  stages {

    stage('Bundlewatch') {
      when {
        allOf {
          not { changelog '.*^Automated release [0-9\\.]+$' }
          not { buildingTag() }
        }
      }
      steps {
        node(label: 'docker') {
          sh '''pnpm install'''
          sh '''make develop'''
          sh '''pnpm build'''
          sh '''pnpm exec bundlewatch --config .bundlewatch.config.json'''
        }
      }
    }

    stage('Docker test build') {
      when {
        allOf {
          not { changelog '.*^Automated release [0-9\\.]+$' }
          not { buildingTag() }
        }
      }
      steps {
        node(label: 'docker') {
          script {
            dockerImage = docker.build("${registry}", ".")
          }
        }
      }
    }

    stage('Release') {
      when {
        allOf {
          anyOf {
            buildingTag()
            branch 'master'
          }
        }
      }
      steps {
        node(label: 'docker') {
          withCredentials([string(credentialsId: 'eea-jenkins-token', variable: 'GITHUB_TOKEN')]) {
            sh '''docker run -i --rm --pull always --name="$BUILD_TAG-gitflow-master" -e GIT_BRANCH="$BRANCH_NAME" -e GIT_NAME="$GIT_NAME" -e GIT_TOKEN="$GITHUB_TOKEN" -e LANGUAGE=frontend eeacms/gitflow'''
          }
        }
      }
    }

    stage('Pull Request') {
      when {
        not {
          changelog ''
        }
        environment name: 'CHANGE_TARGET', value: 'master'
      }
      steps {
        node(label: 'docker') {
          withCredentials([string(credentialsId: 'eea-jenkins-token', variable: 'GITHUB_TOKEN')]) {
            sh '''docker run --pull always -i --rm --name="$BUILD_TAG-gitflow-pr" -e GIT_CHANGE_TARGET="$CHANGE_TARGET" -e GIT_CHANGE_BRANCH="$CHANGE_BRANCH" -e GIT_CHANGE_AUTHOR="$CHANGE_AUTHOR" -e GIT_CHANGE_TITLE="$CHANGE_TITLE" -e GIT_TOKEN="$GITHUB_TOKEN" -e GIT_BRANCH="$BRANCH_NAME" -e GIT_CHANGE_ID="$CHANGE_ID" -e GIT_ORG="$GIT_ORG" -e GIT_NAME="$GIT_NAME" -e LANGUAGE=frontend eeacms/gitflow'''
          }
        }
      }
    }

    stage('SonarQube') {
      when {
        allOf {
          not { changelog '.*^Automated release [0-9\\.]+$' }
          not { buildingTag() }
        }
      }
      steps {
        node(label: 'docker') {
          script {
            def scannerHome = tool 'SonarQubeScanner'
            def nodeJS = tool 'NodeJS'
            if (env.CHANGE_ID) {
              env.sonarParams = " -Dsonar.pullrequest.base=${env.CHANGE_TARGET} -Dsonar.pullrequest.branch=${env.CHANGE_BRANCH} -Dsonar.pullrequest.key=${env.CHANGE_ID} "
            }
            else {
              env.sonarParams = " -Dsonar.branch.name=${env.BRANCH_NAME}"
            }
            withSonarQubeEnv('Sonarqube') {
              sh "export PATH=${scannerHome}/bin:${nodeJS}/bin:$PATH; sonar-scanner -Dsonar.sources=./src -Dsonar.projectKey=$GIT_NAME -Dsonar.projectName=$GIT_NAME -Dsonar.projectVersion=\\$(jq -r '.version' package.json) ${env.sonarParams}"
              sh '''try=5; while [ \$try -gt 0 ]; do curl -s -XPOST -u "${SONAR_AUTH_TOKEN}:" "${SONAR_HOST_URL}api/project_tags/set?project=${GIT_NAME}&tags=${SONARQUBE_TAG}" > set_tags_result; if [ \$(grep -ic error set_tags_result ) -eq 0 ]; then try=0; else cat set_tags_result; echo "... Will retry"; sleep 15; try=\$(( \$try - 1 )); fi; done'''
            }
          }
        }
      }
    }

  }

  post {
    always {
      cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenSuccess: true, cleanWhenUnstable: true, deleteDirs: true)
    }
    changed {
      script {
        def details = """<h1>${env.JOB_NAME} - Build #${env.BUILD_NUMBER} - ${currentBuild.currentResult}</h1>
                         <p>Check console output at <a href="${env.BUILD_URL}/display/redirect">${env.JOB_BASE_NAME} - #${env.BUILD_NUMBER}</a></p>
                      """
        emailext(
        subject: '$DEFAULT_SUBJECT',
        body: details,
        attachLog: true,
        compressLog: true,
        recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'CulpritsRecipientProvider']]
        )
      }
    }
  }
}
